# Maximum coverage: brands + generic + Hindi + game types + apps
KEYWORDS = [
    # --- Top brands India ---
    "1xbet",
    "betway India",
    "parimatch",
    "pin-up casino",
    "mostbet",
    "melbet",
    "1win",
    "linebet",
    "betwinner",
    "dafabet India",
    "bet365 India",
    "10cric",
    "fun88",
    "pure win",
    "casumo India",
    "leovegas India",
    "betmaster",
    "rajabets",
    "megapari",
    "4rabet",
    "crickex",
    "fairplay club",
    "lotus365",
    "world777",
    "diamondexch",
    "skyexchange",
    "laser247",
    "tigerexch",
    "lordsexch",
    "gold365",
    "silverexch",

    # --- Generic gambling English ---
    "online casino India",
    "casino bonus India",
    "live casino India",
    "slots real money",
    "win real money",
    "jackpot India",
    "casino app download",
    "best casino app",
    "real money casino",
    "casino deposit bonus",
    "free spins India",
    "no deposit bonus",
    "welcome bonus casino",
    "VIP casino",

    # --- Card games ---
    "teen patti real cash",
    "teen patti gold",
    "teen patti master",
    "3 patti online",
    "andar bahar online",
    "andar bahar real money",
    "poker online India",
    "poker real money",
    "blackjack India",
    "baccarat online",
    "dragon tiger game",
    "jhandi munda online",

    # --- Rummy ---
    "rummy online",
    "rummy real cash",
    "rummy app download",
    "rummy circle",
    "rummy culture",
    "a23 rummy",
    "junglee rummy",
    "rummy bo",
    "holy rummy",
    "rummy gold",
    "rummy nabob",
    "rummy modern",
    "rummy ola",
    "rummy loot",
    "rummy perfect",
    "rummy east",
    "rummy west",

    # --- Crash / instant games ---
    "aviator game",
    "aviator predictor",
    "aviator app",
    "aviator hack",
    "JetX game",
    "spaceman game",
    "mines game casino",
    "plinko game",
    "lucky jet",
    "crash game real money",

    # --- Sports betting ---
    "cricket betting app",
    "cricket betting tips",
    "IPL betting",
    "IPL prediction",
    "cricket satta",
    "sports betting app",
    "football betting India",
    "kabaddi betting",
    "horse racing India",
    "live betting app",
    "match prediction",
    "betting tips today",
    "best betting app India",
    "online satta",
    "satta matka",

    # --- Fantasy ---
    "fantasy cricket",
    "fantasy app",
    "dream11 alternative",
    "fantasy sports real money",
    "my11circle",
    "vision11",
    "myteam11",

    # --- Hindi keywords ---
    "ऑनलाइन कैसीनो",
    "जीतो असली पैसा",
    "कैसीनो बोनस",
    "क्रिकेट सट्टा",
    "तीन पत्ती",
    "रमी गेम",
    "पैसे कमाओ",
    "असली पैसे का गेम",
    "सट्टा मटका",
    "एविएटर गेम",
    "लाइव कैसीनो",
    "पोकर ऑनलाइन",
    "बेटिंग ऐप",
    "पैसे जीतो",

    # --- Lure phrases (common in creatives) ---
    "earn money online game",
    "daily income app",
    "withdraw to bank",
    "UPI withdrawal",
    "instant withdrawal casino",
    "paytm casino",
    "PhonePe withdrawal",
    "earn 50000 daily",
    "play and earn",
    "refer and earn casino",
    "colour prediction",
    "color prediction game",
    "colour trading",
    "wingo game",
    "fast parity",
    "big small prediction",
    "lottery India online",
    "lucky draw",
]
